name: Test Build & Deploy

on:
  push:
    branches:
      - main    # change to main if needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python unit_tests.py

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t atanubiswas/eric-robotics-psipl:latest .

      - name: Push the Docker image
        run: docker push atanubiswas/eric-robotics-psipl:latest

  deploy:
    name: Deploy app
    runs-on: self-hosted
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Docker Pull & Run Image 
        uses: appleboy/ssh-action@master
        with:
          host: 13.201.22.253
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script_stop: true
          port: 22
          script: |
            whoami
            cd /home/ubuntu/ERIC-Robotics-PSIPL
            pwd
            docker stop atanubiswas/eric-robotics-psipl || true
            docker rmi atanubiswas/eric-robotics-psipl || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/eric-robotics-psipl:latest
            docker run -d --name eric-robotics-psipl -p 6000:6000 ${{ secrets.DOCKERHUB_USERNAME }}/eric-robotics-psipl:latest
