name: Test Build & Deploy

on:
  push:
    branches:
      - main    # change to main if needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python unit_tests.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          contex: .
          push: true
          tags: atanubiswas/webapp:${{ github.sha }}

  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: applyboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker stop webapp || true
            docker rm webapp || true
            docker pull ${{ secrets.DOCKERHUB.USERNAME }}/webapp:${{ github.sha }}
            docker run -d --name webapp -p 5000:5000 ${{ secrets.DOCKERHUB.USERNAME }}/webapp:${{ github.sha }}

     
