name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python unit_tests.py

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.AWS_HOST_IP }} "\
            cd ERIC-Robotics-PSIPL && \
            git pull origin main && \
            pip install -r requirements.txt && \
            python app.py"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
