name: Fly Deploy

on:
  push:
    branches:
      - main    # change to main if needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python unit_tests.py

  deploy:
    name: Deploy app
    runs-on: self-hosted
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa


      - name: Deploy to EC2
        run: |
          cd /home/ubuntu/ERIC-Robotics-PSIPL
          git pull origin main
          pip install -r requirements.txt
          python3 app.py
